development:
  adapter: postgresql
  database: sitelara_development
  user: andre
  password: andre
  host: localhost
  poor: 5

test:
  adapter: postgresql
  database: sitelara_test
  user: andre
  password: andre
  host: localhost
  poor: 5

production:
  adapter: postgresql
  database: sitelara_production
  host: localhost
  poor: 5
