development:
  adapter: postgresql
  database: sitelara_development
  host: localhost
  poor: 5

test:
  adapter: postgresql
  database: sitelara_test
  host: localhost
  poor: 5

production:
  adapter: postgresql
  database: sitelara_production
  host: localhost
  poor: 5